function(rwkv_mobile_patch_llama_cpp_android_mmap source_file)
    file(READ "${source_file}" source_text)
    set(original "        if (numa) { prefetch = 0; }\n")
    set(replacement "${original}#ifdef __ANDROID__\n        // Keep Android mappings lazy; whole-file population stalls compatibility graphics IPC.\n        prefetch = 0;\n#endif\n")

    string(FIND "${source_text}" "${replacement}" already_patched)
    if (NOT already_patched EQUAL -1)
        return()
    endif()
    string(FIND "${source_text}" "${original}" patch_at)
    if (patch_at EQUAL -1)
        message(FATAL_ERROR "Pinned llama.cpp mmap source no longer matches the reviewed Android patch")
    endif()
    string(REPLACE "${original}" "${replacement}" patched_text "${source_text}")
    file(WRITE "${source_file}" "${patched_text}")
    message(STATUS "Disabled whole-file mmap population in pinned llama.cpp on Android")
endfunction()
